// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const UPDATE_AUTH = 'UPDATE_AUTH';

// WEBTOON
export const WEBTOON_LIST_REQUEST = 'WEBTOON_LIST_REQUEST';
export const UPDATE_WEBTOON_LIST_STATE = 'UPDATE_WEBTOON_LIST_STATE';
export const LIKE_LIST_REQUEST = "LIKE_LIST_REQUEST";